### ISSUE TITLE
Workers sit idle at low RCL levels

### ISSUE THREAD

**Issue by rooklion** [bencbartlett/Overmind#4]
### Description of issue:
Early on in a new room, specifically during a fresh respawn, the basic worker_# creeps sit idle for many ticks, sometimes their entire lifecycle.  Construction sites exist for roads exist, but workers are not assigned tasks.  Sometimes some of the workers will have a task and others will sit idle.

### Steps to reproduce:
Respawn into a fresh room.  Set up roomPlanner flags.  Finalize.  Wait for construction sites to appear and worker_# creeps to begin spawning.

### Error message:
N/A

// Console output:
N/A

### Other information:
- Overmind version: 0.2.0
    - Commit hash: {Please include the commit hash if known}
- Issue is with dependency: No

The screenshot attached is a fresh respawn; miners have recently completed their first container, and workers began spawning.  All of them sat idle at the spawner, not being assigned a task.

https://imgur.com/a/doKOm7V

**Comment by bencbartlett** [comment]
Workers are [only allowed to withdraw](https://github.com/bencbartlett/Overmind/blob/master/src/overlords/core/overlord_work.ts#L144) from containers which have at least `WorkerOverlord.settings.workerWithdrawLimit` energy (750 at early stages), so they are idling until enough energy is accumulated that they are allowed to withdraw. This is to ensure that transporters get resource priority; otherwise, workers could saturate all available energy and spawns would be choked, resulting in a colony crash. 

I could add some functionality which prevents workers from spawning until sufficient room energy is available, but this would be pretty low priority; feel free to create a pull request if you'd like to add this.

**Comment by bencbartlett** [comment]
Accidentally closed issue

**Comment by rooklion** [comment]
I will keep an eye out, but I seem to recall workers sitting idle even after they have withdrawn energy or some left over from a previous job.  If I encounter the same, I will post a follow-up.

**Comment by bencbartlett** [comment]
> sitting idle even after they have withdrawn energy

Workers can withdraw energy, then all containers in the room can drop below 750 energy, preventing the worker from withdrawing again until 750 energy is reached.

> some left over from a previous job

If you find a worker that is sitting idle with energy in its carry, that would be a new bug I've not seen before; please open a new issue. Including the contents of `worker.memory.task` would be helpful in that case.

**Comment by bencbartlett** [comment]
This has been fixed in v0.3.1 in this commit: https://github.com/bencbartlett/Overmind/commit/1f6049d56fb566133c3ee8ed50c71c95fb5b9d75

Closing this issue now.
