### ISSUE TITLE
Tune the room selection algorithm

### ISSUE THREAD

**Issue by MaggNorway** [bencbartlett/Overmind#44]
### Motivation:

On a private testserver w/o other bots, Overmind has 3xO and 3xH at GCL6. It could have been better balanced.

These rooms are the standard private server setup, if one wants to reproduce the behavior. Initial room W8N6.

![screenshot-20180826150321-1376x1301modified](https://user-images.githubusercontent.com/7836813/44628725-03b81280-a946-11e8-97c2-9be5497409bb.png)

**Comment by bencbartlett** [comment]
Rooms are chosen based on a heuristic which includes outpost source proximity, mineral type, distance to other colonies, and proximity to enemies. Mineral type is included in the selection process; looking at the map, it seems like the bot has chosen fairly optimal room placements when all these factors are considered. On public servers, mineral type isn't terribly important because the market is fairly liquid for base resources, and on private servers, you should consider adding [`screepsmod-market`](https://github.com/ScreepsMods/screepsmod-market) for a more complete experience!
