### ISSUE TITLE
Feature Directive Flag(s) Upgraders/Workers

### ISSUE THREAD

**Issue by ryu777mtg** [bencbartlett/Overmind#56]
## Feature request summary

Possibly the ability to place a flag which would allow for more upgraders/workers to spawn and start working in a particular location.

### Motivation:

To be able to control how fast you can upgrade your RCL and ramparts on the fly.

### Description:

Ability to place/remove directive flag as necessary to cause the spawn to start spawning more workers/upgraders to move to said location and begin work to speed up process. Might need two separate flags one for each. The ability to remove the flag would cause the spawner to go back to normal so if you notice your resources declining you could stop the spawning.

### Related issues:

Not sure if it's an issue I just notice towards the later RCL lvls that you become limited to only about 2 upgraders and 1 worker as of early RCL lvls you have a swarm of about 5+.

**Comment by bencbartlett** [comment]
Balancing worker/upgrader/miner/transporter quantities is a tricky problem, which, if done incorrectly, can lead to a colony collapse. The current system could use a bit more improvement, especially at early RCL, but in the steady state will eventually reach equilibrium, since the number of upgraders scales with the amount of stored energy, and workers are spawned to fortify ramparts above a certain threshold. Adding ways to manually tweak this would (1) go against the "automate-everything" design direction and (2) would be asking for trouble, as the current system is already fairly well optimized. (I actually screwed myself over in the last BotArena round by making a very minor last-minute economy balance change which crippled my bot's performance.)

Closing this request now, but thanks for submitting it. If you have thoughts on fully automated ways to improve economy balance, feel free to make another one.
